name: URBAN MEDINA
favicon: null
layout_spectrum: 0.88235
typography_spectrum: 0.1475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfffd'
    - '#84776f'
    - '#46494e'
    - '#8bcff6'
    - '#c9bea8'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
